# Generated by Django 3.0.8 on 2020-08-30 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='types1',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='list.types'),
            preserve_default=False,
        ),
    ]
