# Generated by Django 3.0.8 on 2020-08-30 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0002_items_types1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='rate',
            field=models.IntegerField(),
        ),
    ]
