# Generated by Django 3.0.8 on 2020-08-30 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0005_auto_20200830_1703'),
    ]

    operations = [
        migrations.CreateModel(
            name='save_order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types1', models.CharField(max_length=50)),
                ('item_name', models.CharField(max_length=50)),
                ('quantity', models.IntegerField(default=1)),
                ('rate', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='pics')),
                ('name1', models.CharField(max_length=20)),
                ('contact1', models.IntegerField()),
                ('contact2', models.IntegerField()),
                ('address', models.TextField(max_length=500)),
                ('pincode', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='items',
            name='des',
            field=models.TextField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
