# Generated by Django 3.0.8 on 2020-08-30 12:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0006_auto_20200830_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='save_order',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 8, 30, 12, 58, 26, 919667, tzinfo=utc)),
        ),
    ]
