# Generated by Django 3.0.8 on 2020-08-30 15:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0007_save_order_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='save_order',
            name='image',
        ),
        migrations.AddField(
            model_name='save_order',
            name='total',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='save_order',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 8, 30, 15, 33, 42, 32866, tzinfo=utc)),
        ),
    ]
