# Generated by Django 3.0.8 on 2020-08-31 04:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0008_auto_20200830_2103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='name1',
            new_name='item_name',
        ),
        migrations.AlterField(
            model_name='save_order',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 8, 31, 4, 10, 27, 626012, tzinfo=utc)),
        ),
    ]
