# Generated by Django 3.0.8 on 2020-08-31 05:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0010_auto_20200831_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='save_order',
            name='item_id',
            field=models.CharField(default=0, max_length=100000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='save_order',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 8, 31, 5, 27, 32, 446280, tzinfo=utc)),
        ),
    ]
