# Generated by Django 3.0.8 on 2020-08-31 09:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0012_auto_20200831_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='save_order',
            name='contact1',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='save_order',
            name='contact2',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='save_order',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 8, 31, 9, 29, 25, 53882, tzinfo=utc)),
        ),
    ]
