# Generated by Django 3.0.8 on 2020-08-31 09:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0013_auto_20200831_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='save_order',
            name='district',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='save_order',
            name='state',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='save_order',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 8, 31, 9, 51, 30, 977086, tzinfo=utc)),
        ),
    ]
