# Generated by Django 3.0.8 on 2020-09-03 04:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0016_auto_20200831_2111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='types1',
            new_name='product_type',
        ),
        migrations.RenameField(
            model_name='types',
            old_name='types1',
            new_name='product_type',
        ),
        migrations.RemoveField(
            model_name='items',
            name='des',
        ),
        migrations.AddField(
            model_name='items',
            name='desecription',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='save_order',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 9, 3, 4, 4, 40, 552741, tzinfo=utc)),
        ),
    ]
