# Generated by Django 3.0.8 on 2020-09-03 05:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0017_auto_20200903_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='image',
            field=models.ImageField(default=0, upload_to='pics/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='save_order',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 9, 3, 5, 29, 25, 683530, tzinfo=utc)),
        ),
    ]
